---
- hosts: all
  become: true
  tasks:

    - name: Installing packages
      package:
        name:
          - "{{ apache_package}}"
          - "{{ nginx_package}}"
        state: absent
        update_cache: yes
       
