---
- hosts: all
  become: true

  tasks:
    - name: Chack and update server
      apt:
        update_cache : yes
    
    - name: Remove Apache2
      apt:
        name: apache2
        state: absent
